In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\asnsu\ICT\Assignment 1\auto-mpg.csv")

In [6]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

1. Basic Array Operations
Convert the mpg column into a NumPy array and calculate:
○ The mean, median, and standard deviation of mpg.
○ The number of cars with mpg greater than 25.

In [ ]:
mpg_array = df["mpg"].values

In [8]:
mpg_array

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [9]:
import numpy as np

mpg_mean = np.mean(mpg_array)
mpg_median = np.median(mpg_array)
mpg_std = np.std(mpg_array)

print("Mean:", mpg_mean)
print("Median:", mpg_median)
print("Standard Deviation:", mpg_std)

Mean: 23.514572864321607
Median: 23.0
Standard Deviation: 7.806159061274433


In [10]:
num_cars_gt_25 = np.sum(mpg_array > 25)
print("Number of cars with mpg greater than 25:", num_cars_gt_25)

Number of cars with mpg greater than 25: 158


Filtering
Using NumPy, filter all cars with more than 6 cylinders.
Return the corresponding car_name as a list

In [ ]:
car_name = df["car name"].values[df["cylinders"].values > 6].tolist()
car_name

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

Statistical Analysis
Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy

In [ ]:
weight_array = df["weight"].values
q1 = np.percentile(weight_array, 25)
q2 = np.percentile(weight_array, 50)
q3 = np.percentile(weight_array, 75)

print("25th percentile:", q1)
print("50th percentile:", q2)
print("75th percentile:", q3)

25th percentile: 2223.75
50th percentile: 2803.5
75th percentile: 3608.0


In [21]:
weight_array

array([3504, 3693, 3436, 3433, 3449, 4341, 4354, 4312, 4425, 3850, 3563,
       3609, 3761, 3086, 2372, 2833, 2774, 2587, 2130, 1835, 2672, 2430,
       2375, 2234, 2648, 4615, 4376, 4382, 4732, 2130, 2264, 2228, 2046,
       2634, 3439, 3329, 3302, 3288, 4209, 4464, 4154, 4096, 4955, 4746,
       5140, 2962, 2408, 3282, 3139, 2220, 2123, 2074, 2065, 1773, 1613,
       1834, 1955, 2278, 2126, 2254, 2408, 2226, 4274, 4385, 4135, 4129,
       3672, 4633, 4502, 4456, 4422, 2330, 3892, 4098, 4294, 4077, 2933,
       2511, 2979, 2189, 2395, 2288, 2506, 2164, 2100, 4100, 3672, 3988,
       4042, 3777, 4952, 4464, 4363, 4237, 4735, 4951, 3821, 3121, 3278,
       2945, 3021, 2904, 1950, 4997, 4906, 4654, 4499, 2789, 2279, 2401,
       2379, 2124, 2310, 2472, 2265, 4082, 4278, 1867, 2158, 2582, 2868,
       3399, 2660, 2807, 3664, 3102, 2875, 2901, 3336, 1950, 2451, 1836,
       2542, 3781, 3632, 3613, 4141, 4699, 4457, 4638, 4257, 2219, 1963,
       2300, 1649, 2003, 2125, 2108, 2246, 2489, 23

Array Manipulation
Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [ ]:
acceleration_array = df["acceleration"].values
acceleration_norm = (acceleration_array - acceleration_array.min()) / (
    acceleration_array.max() - acceleration_array.min()
)
acceleration_norm

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

Broadcasting
Increase all horsepower values by 10% and store the updated values in a new
NumPy array. Handle missing data (if any) by replacing it with the mean of the
column before applying the increase.

In [ ]:
horsepower = pd.to_numeric(df["horsepower"], errors="coerce")

mean_hp = np.nanmean(horsepower)
horsepower_filled = np.where(np.isnan(horsepower), mean_hp, horsepower)

horsepower_updated = horsepower_filled + horsepower_filled * 0.1
horsepower_updated

array([143.        , 181.5       , 165.        , 165.        ,
       154.        , 217.8       , 242.        , 236.5       ,
       247.5       , 209.        , 187.        , 176.        ,
       165.        , 247.5       , 104.5       , 104.5       ,
       106.7       ,  93.5       ,  96.8       ,  50.6       ,
        95.7       ,  99.        , 104.5       , 124.3       ,
        99.        , 236.5       , 220.        , 231.        ,
       212.3       ,  96.8       ,  99.        , 104.5       ,
       114.91632653, 110.        , 115.5       , 110.        ,
        96.8       , 110.        , 181.5       , 192.5       ,
       168.3       , 165.        , 198.        , 187.        ,
       192.5       , 121.        ,  79.2       , 110.        ,
        96.8       ,  94.6       ,  99.        ,  77.        ,
        83.6       ,  71.5       ,  75.9       ,  66.        ,
        77.        , 104.5       ,  88.        ,  59.4       ,
        99.        ,  94.6       , 181.5       , 192.5 

Boolean Indexing
Find the average displacement of cars with an origin of 2 (Europe) using NumPy
indexing

In [ ]:
avg_displacement_europe = np.mean(df["displacement"].values[df["origin"].values == 2])
print("Average displacement of cars with origin 2 (Europe):", avg_displacement_europe)

Average displacement of cars with origin 2 (Europe): 109.14285714285714


Matrix Operations
Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].


In [16]:
matrix = np.column_stack((mpg_array, horsepower_filled, weight_array))
vector = np.array([1, 0.5, -0.2])
dot_product = np.dot(matrix, vector)
dot_product

array([-617.8       , -641.1       , -594.2       , -595.6       ,
       -602.8       , -754.2       , -746.8       , -740.9       ,
       -758.5       , -660.        , -612.6       , -627.8       ,
       -662.2       , -490.7       , -402.9       , -497.1       ,
       -488.3       , -453.9       , -355.        , -318.        ,
       -465.9       , -417.        , -402.5       , -364.3       ,
       -463.6       , -805.5       , -765.2       , -760.4       ,
       -840.9       , -355.        , -379.8       , -373.1       ,
       -331.96530612, -457.8       , -619.3       , -598.8       ,
       -597.4       , -589.6       , -745.3       , -791.3       ,
       -740.3       , -730.2       , -889.        , -851.2       ,
       -927.5       , -519.4       , -423.6       , -587.4       ,
       -565.8       , -378.        , -351.6       , -349.8       ,
       -345.        , -291.1       , -253.1       , -309.8       ,
       -330.        , -384.1       , -360.2       , -400.8    

Sorting
Use NumPy to sort the cars by model_year in descending order and display the first
five car names.

In [ ]:
car_names_sorted = (
    df.sort_values("model year", ascending=False)["car name"].head(5).tolist()
)
car_names_sorted

['chevy s-10', 'ford ranger', 'dodge rampage', 'vw pickup', 'ford mustang gl']

Correlation
Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [18]:
corr_coef = np.corrcoef(mpg_array, weight_array)[0, 1]
print("Pearson correlation coefficient between mpg and weight:", corr_coef)

Pearson correlation coefficient between mpg and weight: -0.8317409332443354


Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [ ]:
unique_cylinders = np.unique(df["cylinders"].values)
mean_mpg_by_cyl = {
    cyl: np.mean(mpg_array[df["cylinders"].values == cyl]) for cyl in unique_cylinders
}
mean_mpg_by_cyl

{np.int64(3): np.float64(20.55),
 np.int64(4): np.float64(29.28676470588235),
 np.int64(5): np.float64(27.366666666666664),
 np.int64(6): np.float64(19.985714285714284),
 np.int64(8): np.float64(14.963106796116506)}